[tool.ruff]
line-length = 88
exclude = [".venv", "__pycache__", "migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "W", "C90"]  # C90 = McCabe
extend-ignore = ["E203", "B008"]
per-file-ignores = { "__init__.py" = ["F401"] }

[tool.ruff.lint.mccabe]
max-complexity = 10