version: 1
disable_existing_loggers: false

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s | %(levelprefix)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [default]
    propagate: false

#  watchfiles:
#    level: WARNING
#    handlers: [ default ]
#    propagate: false

root:
  level: INFO
  handlers: [default]
